server:
  port: 8080

app:
  rs-module-url: http://localhost:8081/rs
  # OK, NOT_FOUND, SERVICE_DISCOVERY, TIMEOUT
  mode: OK

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
      circuitbreaker:
        enabled: false

logging.level:
  com.example.feign: DEBUG